#### general settings
# name: MYNET
use_tb_logger: true

fs : 16000
chunk_time : 4
least_time : 2

REVERB_2MIX:
  select_mode : 2 # 1 : train, 2: development, 3: evaluation
  num_spks : 2
  scp_list : /home/nas/user/hogun/NN_BSS/dataset/REVERB/etc/
  tr_parent_wave_list : /home/nas/user/hogun/NN_BSS/dataset/REVERB/tr/data/
  dt_parent_wave_list : /home/nas/user/hogun/NN_BSS/dataset/REVERB/dt/data/
  saved_tr_pickle_dir : /home/data/hogun/REVERB/tr/
  saved_dt_pickle_dir : /home/data/hogun/REVERB/dt/

STFT:
  fs : 16000
  window : hann
  length : 512 #32ms
  overlap : 128 #8ms

# Task related

# #### datasets
# datasets:
#   train: '/home/hogun/SED/coding/Bluekite/data/'
#   valid: '/home/hogun/SED/coding/Bluekite/data/'
#   test: '/home/hogun/SED/coding/Bluekite/data/'
#   extraction : '/home/hogun/SED/coding/Bluekite/data/'
#   select_testdata : A  #'A', 'B', 'C', 'D' defalt = 'A'
#   C_B : 'C' #'C', 'B'
  
# extraction:
#   target_mode: 1 #1: (S S) 2 : (Q Q), 3 : (Q S), 4: (S Q) 
#   tau: 1.5
#   v: 0.3
#   segLen: 1
#   feature_onoff: 1
#   spec_augmentation : True

dataloader:
  Train:
    batch_size: 128
    shuffle: True
    num_workers: 0

  Development:
    batch_size: 128
    shuffle: False
    num_workers: 0

  Evaluation:
    batch_size: 1
    shuffle: false
    num_workers: 50

# #### network structures
MISO_1:
  num_bottleneck : 8
  Ch : 8  # number of mic
  Spk : 2 # number of speaker
  norm_type : IN  #Instance Norm

#### Optimizer settings
trainer:
  epochs : 50
  device : 1
  save_path : ./model_saved/


optimizer:
  name: Adam   ### Adam, RMSprop, SGD
  lr: !!float 1e-3  #Init learning rqte
  weight_decay: 0.0 #weight decay
  


# #MYNEY(Block_Model, layers, num_classes, in_channels)

# #### training settings: learning rate scheme, loss
# trainer:
#   dataset_name: MIVIA
#   save_path: ./ckpt/MIVAI/RESNET
#   epochs: 1000
#   device: 1
#   p : 0.5
#   # load_ckpt: false

# tester:
#   p : 0.5
#   ckpt_path: ./ckpt/RWF/617_3.3689.pt
#   device: 0


# criterion:
#   # name: CTCLoss
#   name: focal_loss


  

# #### scheduler settings
# scheduler:
#   name: plateau
#   min_lr: !!float 1e-8
#   patience: 2
#   threshold : 0.0001
#   threshold_mode : abs
#   cooldown : 0
#   factor: 0.5

# # #### Resume training settings
# # resume:
# #   state: false
# #   path: /home/minseok/Dual-Path-RNN/checkpoint


# # #### logger
# # logger:
# #   name: DPCL
# #   path: /home/minseok/Dual-Path-RNN-Pytorch/checkpoint
# #   screen: false
# #   tofile: true
#   # print_freq: 1000